import {BuyCourse, Landing, StuDashboard, StudentLogin, TutorLogin, TutorDashboard, Flashcards, AddCourse,CourseDetails, CreateFlashCards, StuReg, TutorReg} from "../Pages";
// import Flashcards from "../Pages/Flashcards";

const routes = [
    {title:"Landing",
    path:"/",
    description:"Landing Page",
    element:<Landing/>,
    },
    {title:"StuReg",
    path:"/studentRegister",
    description:"Student Regiser",
    element:<StuReg/>,
    },
    {title:"TutorReg",
    path:"/tutorRegister",
    description:"Tutor Regiser",
    element:<TutorReg/>,
    },
    {title:"StudentLogin",
    path:"/studentLogin",
    description:"Student Login",
    element:<StudentLogin/>,
    },
    {title:"TutorLogin",
    path:"/tutorLogin",
    description:"tutor login",
    element:<TutorLogin/>,
    },
    {title:"StuDashboard",
    path:"/stuDashboard",
    description:"Student Dashbaord",
    element:<StuDashboard/>,
    },
    {title:"TutorDashboard",
    path:"/tutorDashboard",
    description:"Tutor Dashbaord",
    element:<TutorDashboard/>,
    },
    {title:"BuyCourse",
    path:"/buyCourse",
    description:"Buy course",
    element:<BuyCourse/>,
    },
    {title:"Flashcards",
    path:"/flashcards",
    description:"Flash cards",
    element:<Flashcards/>,
    },
    {title:"AddCourse",
    path:"/addCourse",
    description:"Add Course",
    element:<AddCourse/>,
    },
    {title:"CourseDetails",
    path:"/course",
    description:"Course details",
    element:<CourseDetails/>,
    },
    {title:"CreateFlashCards",
    path:"/createFlashcards",
    description:"FlashCards update",
    element:<CreateFlashCards/>,
    },
]

export default routes