// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Course struct {
	ID         uuid.UUID
	Langtaught string
	TutorID    uuid.UUID
	Takenby    int32
	Price      int32
	Coursename sql.NullString
}

type Coursesub struct {
	ID        uuid.UUID
	StudentID uuid.UUID
	CourseID  uuid.UUID
}

type Flashcard struct {
	ID       uuid.UUID
	CourseID uuid.UUID
	Word     string
	Meaning  string
}

type Slot struct {
	ID       uuid.UUID
	TutorID  uuid.UUID
	Fromtime time.Time
	Totime   time.Time
	Taken    bool
}

type Student struct {
	ID       uuid.UUID
	Name     string
	Emailid  string
	Passcode string
}

type Tutor struct {
	ID        uuid.UUID
	Name      string
	Emailid   string
	CreatedAt time.Time
	Passcode  string
}
